### ISSUE TITLE
Getting created 201 uploading is not working..

### ISSUE THREAD

**Issue by c0d33py** [edihasaj/tuspy-fast-api#1]
I am tring to upload the file using this package. i am getting `127.0.0.1:53810 - "POST /files/ HTTP/1.1" 201 Created` upload is not started on this API. i am using `tus-client-js` in frontent.

**Comment by edihasaj** [comment]
okay, let me see it. I will fix it now

**Comment by edihasaj** [comment]
@c0d33py please try out the latest:

https://pypi.org/project/tuspyserver/1.1.0/

or you can clone the package and run locally that way you can see how it works the best.

let me know if it fixes the issue or not

**Comment by edihasaj** [comment]
you can run the app and go to /static/uppy.html and try it out

**Comment by edihasaj** [comment]
Closing this as solved due to inactivity. I did test though..., if you have any issues feel free to reopen

**Comment by Fusion86** [comment]
I had the same issue when using tus-client-js and what fixed it for me is adding expose_headers like shown below.
I don't know if all of these are needed, I just got them from https://github.com/tusdotnet/tusdotnet/blob/d876b17ca5d80d9bfb1f27edf7ba584b7c47722f/Source/tusdotnet/Helpers/CorsHelper.cs#L12

```py
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=[
        "Location",
        "Tus-Resumable",
        "Tus-Version",
        "Tus-Extension",
        "Tus-Max-Size",
        "Tus-Checksum-Algorithm",
        "Upload-Length",
        "Upload-Offset",
        "Upload-Metadata",
        "Upload-Checksum",
        "Upload-Concat",
        "Upload-Expires",
    ],
)
```
