### ISSUE TITLE
tus.py is wrong version

### ISSUE THREAD

**Issue by dablenparty** [edihasaj/tuspy-fast-api#47]
I noticed that after merging in #33, there were more changes than simply running `isort` and `black`. It changed parameters to some functions and I'm not entirely sure what else. I noticed after trying to fork the repo because I ran `main.py` and got the error `TypeError: create_api_router() got an unexpected keyword argument 'location'`. PyPi has the correct version, but this repo somehow does not.

**Comment by malnossi** [comment]
Hi there, I'am the owner of the last merged commit, and I think that the owner of this repo didn't push the new version to Pypi.

If you have somme issues you can write me, I would like to help

**Comment by edihasaj** [comment]
Hi, I will make sure today that the latest version with your changes is pushed. Thanks

**Comment by edihasaj** [comment]
@dablenparty & @malnossi I just pushed my changes again to: https://pypi.org/project/tuspyserver/2.1.0/, @malnossi I will make you contributer so that you can make changes as needed

**Comment by malnossi** [comment]
Thank you so much, I will do my best

**Comment by edihasaj** [comment]
Let me know for the access in pypi, I can also do a pipeline in github actions to publish automatically, otherwise I can give you access directly

**Comment by malnossi** [comment]
I dont have access to pypi, I think it would be better to have a CI/CD pipelines

**Comment by malnossi** [comment]
I will close this issue by the way

**Comment by edihasaj** [comment]
Good, I will add a pipeline

**Comment by edihasaj** [comment]
@malnossi added the pipeline now as well, follow README.md file to see how that will work.
