### ISSUE TITLE
TypeError: 'type' object is not subscriptable on Running an instance

### ISSUE THREAD

**Issue by ElijahGM** [edihasaj/tuspy-fast-api#8]
I am running the test app and run the following issue on app start

```
class FileMetadata(BaseModel):
  File "/Users/elijahmwangi/Library/Python/3.8/lib/python/site-packages/tusserver/metadata.py", line 8, in FileMetadata
    metadata: dict[Any, str]
TypeError: 'type' object is not subscriptable
```

The major issue its running it with python3 i believe

**Comment by edihasaj** [comment]
Can you share the library version you are using?

**Comment by edihasaj** [comment]
@ElijahGM you can try a fix with the latest version: https://pypi.org/project/tuspyserver/1.3.1/
