### ISSUE TITLE
Add authentication?

### ISSUE THREAD

**Issue by hashcutdev** [edihasaj/tuspy-fast-api#9]
Thanks for providing this package! I was wondering if there's an easy way to add authentication to the various endpoints. For my use case, only users that are signed in are allowed to upload a file. So I need to check to make sure a valid user is signed in.

Similarly, for endpoints like download and delete, I want to make sure that the request is from the owner of the file, not just anyone who manages to get the UUID.

Is there a wrapper or a dependency hook or something that can be added to the different endpoints to allow us to implement custom authorization logic?

The only other option I see is to not use the create_api_router( ) function and instead manually copy/paste the routes it creates into a custom endpoint, and then alter the code for each endpoint. That's definitely doable but would be messy and would mean that any updates to the endpoint code in the future won't automatically be propagated, so some sort of wrapper or hook would be preferable if there's a way to do it.

**Comment by edihasaj** [comment]
Yeah, we can add auth dependency you can apply anyway you wants and we call it through Deps().

I need some time though to do the changes, or you can contribute if you want

**Comment by edihasaj** [comment]
@hashcutdev one fast workaround solution that you can do is this example:

```
from fastapi import FastAPI, Request, HTTPException, status
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.responses import Response
from starlette.routing import Match

# Your auth logic goes here
async def auth_middleware(request: Request, call_next: RequestResponseEndpoint):
    if "files" in request.url.path:  # Check if the route belongs to the create_api_router
        token = request.headers.get('Authorization', None)
        if not token or token != "Bearer your_token":  # Substitute with your auth logic
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Unauthorized",
                headers={"WWW-Authenticate": "Bearer"},
            )
    response = await call_next(request)
    return response

app = FastAPI()

# The rest of your app setup code goes here

app.add_middleware(BaseHTTPMiddleware, dispatch=auth_middleware)

app.include_router(
    create_api_router(
        files_dir='/tmp/different_dir', # OPTIONAL
        location='http://127.0.0.1:8000/files', # OPTIONAL
        max_size=128849018880, # OPTIONAL
        on_upload_complete=on_upload_complete, # OPTIONAL
    ),
    prefix="/files"
)
```

**Comment by edihasaj** [comment]
@hashcutdev I just released a new version:

https://pypi.org/project/tuspyserver/1.3.0/

with the functionality you wanted.

checkout the home page for more example, basically now you pass your auth function as a callback parameter and it applies to each function...

```
...
def on_your_specific_auth():
    pass


app.include_router(
    create_api_router(
        files_dir='/tmp/different_dir',
        location='http://127.0.0.1:8000/files',
        max_size=128849018880,
        on_upload_complete=on_upload_complete,
        auth=on_your_specific_auth,
    ),
    prefix="/files"
)
...
```
